In [1]:
#1. What is a Python library? Why ^o we use Python libraries?

"""What is a Python Library?
A Python library is a collection of pre-written code that you can use to perform common tasks. 
It typically includes functions and classes that simplify various programming activities.

Why Do We Use Python Libraries?
Save Time: They provide ready-made solutions, so you don't have to write code from scratch.
Add Functionality: Libraries offer specialized tools for things like data analysis, web development, and machine learning.
Improve Code Quality: Using well-tested libraries reduces bugs and improves performance.
Simplify Complex Tasks: Libraries make it easier to handle complicated tasks with simple commands.

Examples
NumPy: For mathematical operations.
Pandas: For data manipulation.
Matplotlib: For creating charts and graphs.
Requests: For handling HTTP requests."""

"What is a Python Library?\nA Python library is a collection of pre-written code that you can use to perform common tasks. \nIt typically includes functions and classes that simplify various programming activities.\n\nWhy Do We Use Python Libraries?\nSave Time: They provide ready-made solutions, so you don't have to write code from scratch.\nAdd Functionality: Libraries offer specialized tools for things like data analysis, web development, and machine learning.\nImprove Code Quality: Using well-tested libraries reduces bugs and improves performance.\nSimplify Complex Tasks: Libraries make it easier to handle complicated tasks with simple commands.\n\nExamples\nNumPy: For mathematical operations.\nPandas: For data manipulation.\nMatplotlib: For creating charts and graphs.\nRequests: For handling HTTP requests."

In [2]:
#2. What is the difference between Numpy array and List?

"""Difference Between NumPy Array and List

1. Performance
NumPy Array: Faster and more efficient for numerical operations.
List: Slower, especially for large datasets.

2. Storage
NumPy Array: Stores elements of the same type (usually numbers), leading to efficient memory usage.
List: Can store elements of different types (numbers, strings, objects).

3. Functionality
NumPy Array: Supports advanced mathematical and statistical operations (like matrix operations, element-wise computations).
List: Supports basic operations but lacks specialized numerical methods.

4. Size
NumPy Array: Fixed size once created; you need to create a new array to change its size.
List: Dynamic size; you can easily add or remove elements.

5. Syntax for Operations
NumPy Array: Allows vectorized operations (apply operations to entire arrays at once).
import numpy as np
arr = np.array([1, 2, 3])
arr = arr + 1  # Adds 1 to each element

List: Requires loops or list comprehensions for element-wise operations
lst = [1, 2, 3]
lst = [x + 1 for x in lst]  # Adds 1 to each element"""


'Difference Between NumPy Array and List\n\n1. Performance\nNumPy Array: Faster and more efficient for numerical operations.\nList: Slower, especially for large datasets.\n\n2. Storage\nNumPy Array: Stores elements of the same type (usually numbers), leading to efficient memory usage.\nList: Can store elements of different types (numbers, strings, objects).\n\n3. Functionality\nNumPy Array: Supports advanced mathematical and statistical operations (like matrix operations, element-wise computations).\nList: Supports basic operations but lacks specialized numerical methods.\n\n4. Size\nNumPy Array: Fixed size once created; you need to create a new array to change its size.\nList: Dynamic size; you can easily add or remove elements.\n\n5. Syntax for Operations\nNumPy Array: Allows vectorized operations (apply operations to entire arrays at once).\nimport numpy as np\narr = np.array([1, 2, 3])\narr = arr + 1  # Adds 1 to each element\n\nList: Requires loops or list comprehensions for eleme

In [3]:
#3. Fin^ the shape, size an^ ^imension of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Get the shape, size, and dimension
shape = array.shape
size = array.size
dimension = array.ndim

print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)

Shape: (3, 4)
Size: 12
Dimension: 2


In [4]:
#4. Write python co^e to access the first row of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Access the first row
first_row = array[0]

print("First row:", first_row)

First row: [1 2 3 4]


In [5]:
#5. How do you access the element at the third row and fourth column from the given numpy array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Access the element at the third row and fourth column
element = array[2, 3]

print("Element at third row and fourth column:", element)


Element at third row and fourth column: 12


In [8]:
#6. Write code to extract all odd-indexed elements from the given numpy array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Extract all odd-indexed elements
odd_indexed_elements = array[:, 1::2]

print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


In [9]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)

Random 3x3 matrix with values between 0 and 1:
[[0.82234341 0.06458598 0.01082218]
 [0.83993182 0.54441691 0.21859396]
 [0.09174224 0.89712266 0.84691678]]


In [10]:
#8. Describe the difference between np.random.rand and np.random.randn?

"""np.random.rand: This function generates random numbers from a uniform distribution over the interval [0, 1). 
It returns an array of specified shape filled with random values.

np.random.randn: This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
It returns an array of specified shape filled with random values.

Use np.random.rand when you need random numbers from a uniform distribution between 0 and 1.
Use np.random.randn when you need random numbers from a standard normal distribution with mean 0 and standard deviation 1."""

import numpy as np

# Generate a 2x2 matrix using np.random.rand
uniform_random = np.random.rand(2, 2)

# Generate a 2x2 matrix using np.random.randn
normal_random = np.random.randn(2, 2)

print("Random matrix from np.random.rand (uniform distribution):")
print(uniform_random)

print("\nRandom matrix from np.random.randn (standard normal distribution):")
print(normal_random)

Random matrix from np.random.rand (uniform distribution):
[[0.70566417 0.35396116]
 [0.85148442 0.77891558]]

Random matrix from np.random.randn (standard normal distribution):
[[-1.65402209  0.30624947]
 [ 0.04282148  0.65464918]]


In [11]:
#9. Write co^e to increase the ^imension of the following array?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Increase the dimension of the array
new_array = np.expand_dims(array, axis=0)  # Increase dimension along axis 0

print("Original array:")
print(array)

print("\nArray with increased dimension:")
print(new_array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with increased dimension:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [12]:
#10. How to transpose the following array in NumPy?
#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

import numpy as np

# Define the array
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# Transpose the array
transposed_array = np.transpose(array)  # or array.T

print("Original array:")
print(array)

print("\nTransposed array:")
print(transposed_array)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [16]:
"""11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python:
1.index wise multiplication
2.matrix multiplication
3.addboth the matrics
4.substract matrix B from A
5.Divide matrix B by A"""

import numpy as np

# Define the matrices
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 1. Index-wise multiplication
index_wise_multiplication = A * B

# 2. Matrix multiplication
matrix_multiplication = np.dot(A, B.T)  # Transpose of B is taken for matrix multiplication

# 3. Add both the matrices
addition = A + B

# 4. Subtract matrix B from A
subtraction = A - B

# 5. Divide matrix B by A (element-wise division)
division = np.divide(B, A)

print("1. Index-wise multiplication:")
print(index_wise_multiplication)

print("\n2. Matrix multiplication:")
print(matrix_multiplication)

print("\n3. Addition of matrices:")
print(addition)

print("\n4. Subtraction of matrix B from A:")
print(subtraction)

print("\n5. Element-wise division of matrix B by A:")
print(division)

1. Index-wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Addition of matrices:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Subtraction of matrix B from A:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Element-wise division of matrix B by A:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
#12. Which function in Numpy can be used to swap the byte order of an array?
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order
swapped_array = array.byteswap()

print("Original array:", array)
print("Swapped array:", swapped_array)

Original array: [1 2 3 4]
Swapped array: [16777216 33554432 50331648 67108864]


In [18]:
#13. What is the significance of the np.linalg.inv function?

"""Significance of np.linalg.inv:

Undoing Transformations: Imagine you transform a matrix in some way. Want to undo that transformation? np.linalg.inv helps you get back to where you started.
Solving Equations: Got a system of equations? The inverse helps you solve them faster and more efficiently than brute force.
Matrix Magic: In linear algebra, matrices are like the wizards of the numerical world. The inverse is a powerful tool in their spellbook, used for a variety of magical operations.
Error Checking: It's not just about solving equations. You can also use np.linalg.inv to check if a matrix is "invertible" (meaning it has an inverse). If it's not invertible, it's like trying to divide by zero – you'll run into trouble."""

'Significance of np.linalg.inv:\n\nUndoing Transformations: Imagine you transform a matrix in some way. Want to undo that transformation? np.linalg.inv helps you get back to where you started.\nSolving Equations: Got a system of equations? The inverse helps you solve them faster and more efficiently than brute force.\nMatrix Magic: In linear algebra, matrices are like the wizards of the numerical world. The inverse is a powerful tool in their spellbook, used for a variety of magical operations.\nError Checking: It\'s not just about solving equations. You can also use np.linalg.inv to check if a matrix is "invertible" (meaning it has an inverse). If it\'s not invertible, it\'s like trying to divide by zero – you\'ll run into trouble.'

In [19]:
#14. What does the np.reshape function do, and how is it used?

"""What it Does:
Reshaping: Just as you can rearrange furniture in a room, np.reshape rearranges the elements of your array into a new shape.
No Data Change: Like a magic trick, it doesn't change the actual data; it just presents it differently."""
    
import numpy as np

# Define an array
array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a 2x3 matrix
reshaped_array = np.reshape(array, (2, 3))

print("Original array:")
print(array)

print("\nReshaped array:")
print(reshaped_array)

"""Why it's Handy:
Data Flexibility: It lets you mold your data to fit different needs without copying or changing the actual content.
Easy Transformation: Reshaping is a simple way to prepare data for further analysis or processing."""

Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


"Why it's Handy:\nData Flexibility: It lets you mold your data to fit different needs without copying or changing the actual content.\nEasy Transformation: Reshaping is a simple way to prepare data for further analysis or processing."

In [20]:
#15. What is broadcasting in Numpy?

"""What Broadcasting Does:
Shape Matching: Broadcasting helps when you're doing operations on arrays with different shapes.
Automatic Adjustment: It automatically adjusts the smaller array to match the shape of the larger one.
Efficiency: Instead of copying data to match shapes, broadcasting does the operation efficiently without extra memory use.
    
How Broadcasting Works:
Imagine you have a small team of players and a big team. Broadcasting helps make them play together:
If the smaller team can fit into the positions of the bigger team, it's automatically adjusted to match.
Each player from the smaller team performs their task with the corresponding player from the bigger team."""

import numpy as np

# Define arrays
big_team = np.array([[1, 2, 3], [4, 5, 6]])
small_team = np.array([10, 20, 30])

# Add the small team to the big team
result = big_team + small_team

print("Big Team:")
print(big_team)

print("\nSmall Team:")
print(small_team)

print("\nResult of Broadcasting:")
print(result)

"""Why Broadcasting Matters:
Flexibility: You don't need to worry about matching shapes perfectly; broadcasting helps make operations smooth.
Efficiency: It saves memory and speeds up computations by avoiding unnecessary copying."""

Big Team:
[[1 2 3]
 [4 5 6]]

Small Team:
[10 20 30]

Result of Broadcasting:
[[11 22 33]
 [14 25 36]]


"Why Broadcasting Matters:\nFlexibility: You don't need to worry about matching shapes perfectly; broadcasting helps make operations smooth.\nEfficiency: It saves memory and speeds up computations by avoiding unnecessary copying."